# Notebook ( 006-Numpy random )

In [7]:
import numpy


our_array = numpy.random.random(size=(2,3,4))
print(f"Our Array (5,6,8)  : \n\n{our_array}")

our_array = numpy.random.random((2,3,4))
print(f"Our Array (5,6,8)  : \n\n{our_array}")

our_array = numpy.random.random(size=(2))
print(f"Our Array (2)  : \n\n{our_array}")

our_array = numpy.random.random(5)
print(f"Our Array (5)  : \n\n{our_array}")


our_array = numpy.random.randint(100,500,size=(5,3))
print(f"Our Array (5,3) & min=100 and max=500  : \n\n{our_array}")


Our Array (5,6,8)  : 

[[[0.0668092  0.56146578 0.92323681 0.46898915]
  [0.82085482 0.4226414  0.53417165 0.95659606]
  [0.90512784 0.99882191 0.66307257 0.41016015]]

 [[0.24147962 0.50289038 0.83295474 0.06624358]
  [0.55522693 0.4397517  0.58664266 0.75626946]
  [0.81043036 0.00583008 0.65006323 0.33264309]]]
Our Array (5,6,8)  : 

[[[0.07881434 0.52373425 0.35617451 0.09927576]
  [0.16769805 0.46189072 0.08819357 0.29637204]
  [0.03232164 0.90379061 0.06888038 0.78704822]]

 [[0.23302962 0.65107554 0.76060907 0.27343187]
  [0.35104151 0.53943843 0.895382   0.68615422]
  [0.9357902  0.62827309 0.47582591 0.59525115]]]
Our Array (2)  : 

[0.83704775 0.06595158]
Our Array (5)  : 

[0.54617983 0.5954471  0.19682448 0.62165448 0.79027375]
Our Array (5,3) & min=100 and max=500  : 

[[180 238 125]
 [204 151 319]
 [484 203 324]
 [349 401 399]
 [109 393 307]]
