# Notebook ( 008-Numpy Addition & Subtration )

In [1]:
from numpy import subtract,add,ones,full

print(f"{ones(10)+ones(10)}")
print(f"{add(ones(10),ones(10))}")

print(f"{ones(10)-2*ones(10)}")
print(f"{subtract(ones(5),ones(5)+10*ones(5))}")


[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
[-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
[-10. -10. -10. -10. -10.]
