# <center>  Notebook ( 002-Numpy Arrays Creation ) </center>

## 0) Quick Start

| 1 | 2 | 3 |
|---|---|---|

In [2]:
import numpy

our_list = [1,2,3]

our_array = numpy.array(our_list)

print(f"Our 1D Array : \n\n {our_array}")

Our 1D Array : 

 [1 2 3]


| 1 | 2 | 3 |
|---|---|---|
| 5 | 8 | 3 |


In [7]:
import numpy

our_list = [[1,2,3],[5,8,7]]

our_array = numpy.array(our_list)

print(f"Our 2D Array : \n\n {our_array}")

Our 2D Array : 

 [[1 2 3]
 [5 8 7]]


| [1,4,5] | [2,5,6] | [3,7,9] |
|---------|---------|---------|
| [5,7,6] | [8,7,8] | [3,7,9] |


In [ ]:
import numpy

our_list = [[[1,4,5],[2,5,6],[3,7,9]],[[5,7,6],[8,7,8],[3,7,9]]]

our_array = numpy.array(our_list)

print(f"Our 3D Array : \n\n {our_array}")

Our 2D Array : 

 [[[1 4 5]
  [2 5 6]
  [3 7 9]]

 [[5 7 6]
  [8 7 8]
  [3 7 9]]]


##### 1) Manual

In [9]:
import numpy

simple_array = numpy.array([1,2,3,4,5,6])
print(f"Simple array : {simple_array}")

two_d_array = numpy.array([[1,2,3,4,5,6],[1,2,3,4,5,6]])
print(f"2D array : {two_d_array}")

three_d_array = numpy.array([[[1,2],[5,6]],[[1,2],[5,6]],[[1,2],[5,6]],[[1,2],[5,6]],[[1,2],[5,6]],[[1,2],[5,6]]])
print(f"3D array : {three_d_array}")


Simple array : [1 2 3 4 5 6]
2D array : [[1 2 3 4 5 6]
 [1 2 3 4 5 6]]
3D array : [[[1 2]
  [5 6]]

 [[1 2]
  [5 6]]

 [[1 2]
  [5 6]]

 [[1 2]
  [5 6]]

 [[1 2]
  [5 6]]

 [[1 2]
  [5 6]]]


##### 2) Auto-Generate

In [16]:
import numpy

simple_array_with_range = numpy.arange(1,10)
print(f"Array with arrange  : \n\n{simple_array_with_range}")

multiplcation_array = numpy.array([[i*j for j in range(1,10)] for i in range(1,10)])
print(f"Multi array : \n\n{multiplcation_array}")

array_with_random_value = numpy.random.random(size=5)
print(f"Random array values with 1D: \n\n{array_with_random_value}")

array_with_random_value = numpy.random.random(size=(5,4))
print(f"Random array values with 2D : \n\n {array_with_random_value}")


array_with_random_value = numpy.random.random(size=(5,4,4))
print(f"Random array values with 3D : \n\n {array_with_random_value}")


Array with arrange  : 

[1 2 3 4 5 6 7 8 9]
Multi array : 

[[ 1  2  3  4  5  6  7  8  9]
 [ 2  4  6  8 10 12 14 16 18]
 [ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]
 [ 5 10 15 20 25 30 35 40 45]
 [ 6 12 18 24 30 36 42 48 54]
 [ 7 14 21 28 35 42 49 56 63]
 [ 8 16 24 32 40 48 56 64 72]
 [ 9 18 27 36 45 54 63 72 81]]
Random array values with 1D: 

[0.68665741 0.27003028 0.67928425 0.94675581 0.51705532]
Random array values with 2D : 

 [[7.60745655e-01 3.44918073e-01 1.34429057e-01 5.62088850e-01]
 [4.21206754e-01 9.90953585e-02 2.22343824e-01 4.11182749e-02]
 [1.22127655e-01 9.79406428e-01 5.40822067e-01 7.67597717e-01]
 [7.06288819e-01 3.48559860e-02 2.38978898e-01 7.53750966e-04]
 [8.21308498e-01 6.56020919e-01 6.99528002e-01 4.10108505e-01]]
Random array values with 3D : 

 [[[0.85399218 0.76670711 0.24128232 0.9583298 ]
  [0.56472298 0.31349866 0.43958201 0.45651814]
  [0.08177371 0.71675685 0.87286536 0.34802366]
  [0.75407637 0.01838442 0.15528614 0.97598078]]

 [[0.

##### 3) From Files

In [1]:
import numpy

array_with_data_1 = numpy.genfromtxt("./files/data1.txt",delimiter=",")
print(array_with_data_1,end="\n\n")

array_with_data_2 = numpy.genfromtxt("./files/data2.txt",delimiter="-")
print(array_with_data_2,end="\n\n")

array_with_data_2 = numpy.genfromtxt("./files/data2.txt",delimiter="*")
print(array_with_data_2)



[[1. 2. 3. 4. 5. 6.]
 [1. 2. 8. 4. 5. 6.]
 [8. 2. 3. 5. 5. 6.]
 [1. 2. 3. 4. 5. 6.]]

[[1. 2. 3. 4. 5. 6.]
 [1. 2. 8. 4. 5. 6.]
 [8. 2. 3. 5. 5. 6.]
 [1. 2. 3. 4. 5. 6.]]

[nan nan nan nan]
