# Notebook ( 007-Some numpy functions )

In [17]:
from numpy import eye,full,ones,zeros


print(f"Array with eye function \n{eye(5)} ")

print(f"Array with eye function \n{eye(5,k=2)} ")

print(f"Array with eye function with k=-1 \n{eye(5,k=-1)} ")

print(f"Array with full function \n{full(5,101)} ")

print(f"Array with full function \n{full((5,7),100)} ")

print(f"Array with ones function \n{ones(100)} ")

our_array = zeros(100)
our_array = our_array.astype("int32")

print(f"Array with zeros function \n{our_array} ")




Array with eye function 
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] 
Array with eye function 
[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 
Array with eye function with k=-1 
[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]] 
Array with full function 
[101 101 101 101 101] 
Array with full function 
[[100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100]] 
Array with ones function 
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.] 
Array with zeros function 
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 