# Notebook ( Array  reshaping )

### I) Shape

In [1]:
import numpy

array_1d  = numpy.array([1,2,3])
print(f"Array 1D \n {array_1d} \nshape \n {array_1d.shape}",end="\n\n\n")

array_2d  = numpy.array([[1,2],[1,6],[1,3]])
print(f"Array 2D \n {array_2d} \nshape \n {array_2d.shape}",end="\n\n\n")

array_3d  = numpy.array([[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]]])
print(f"Array 3D \n {array_3d} \nshape \n {array_3d.shape}",end="\n\n\n")


Array 1D 
 [1 2 3] 
shape 
 (3,)


Array 2D 
 [[1 2]
 [1 6]
 [1 3]] 
shape 
 (3, 2)


Array 3D 
 [[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]
  [1 2 3]]] 
shape 
 (3, 3, 3)




### II) Reshape

In [6]:
import numpy

sample_array = numpy.arange(1,101)
print(f"Array before the first reshaping :\n\n {sample_array} ") 

print(f"Array after the first reshaping 2D : \n\n{sample_array.reshape(5,20)} ") 

print(f"Array after the second reshaping 2D : \n\n{sample_array.reshape(4,25)} ") 

print(f"Array after the 3rd reshaping 3D : \n\n{sample_array.reshape(2,2,25)} ") 



Array before the first reshaping :

 [  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100] 
Array after the first reshaping 2D : 

[[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
   19  20]
 [ 21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38
   39  40]
 [ 41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58
   59  60]
 [ 61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78
   79  80]
 [ 81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98
   99 100]] 
Array after the second reshaping 2D : 

[[  1   2   3   4   5   6   7   8   9  10  11  12